openshift/windows-machine-config-bootstrapper

Makefile
Signed-off-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>
A test PR to look for CI changes
=> Remove blank line from Makefile

tools/windows-node-installer/README.md
This update refactors the doc for the wni tool.
This PR resolves https://github.com/openshift/windows-machine-config-operator/issues/27.
/cc @ravisantoshgudimetla @sebsoto
=> [docs][wni] README update

tools/windows-node-installer/cmd/aws.go
As of now, we don't need the `AWSOpts` and `createFlagInfo` structs within
`cmd/aws.go` as both of them are being bound from the user provided command
line options, so collapsing them into a single structure
/cc @aravindhp @Bowenislandsong
=> [WNI] Combine unnecessary AWS structs

tools/windows-node-installer/pkg/cloudprovider/factory.go, tools/windows-node-installer/pkg/cloudprovider/factory_test.go
Took over the work from https://github.com/openshift/windows-machine-config-operator/pull/35, I addressed the comments I made https://github.com/openshift/windows-machine-config-operator/pull/35/files#r330166016 and here https://github.com/openshift/windows-machine-config-operator/pull/35/files#r330165612 and added a test suite
I am preserving Bowen's commit to not take credit for some part of his work.
/cc @aravindhp @Bowenislandsong
=> Bug 1757446: [wni] Directory validation errors

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Inject PowerShell script to launch Windows instance and open port `5986` for winrm https
inbound traffic so the windows instance is ready for Ansible communication at
launch and every time it boot up.
Change the `createInstance()` function input with an extra parameter the contains the user data input, which is be either Windows PowerShell command or other. So this function is still generic for all the instance type.
**Another PR with addition feature for telling user that there is an already exist sg that doesn't not contains winrm port and we create creating a new sg that has winrm asscociated with it.**
**Testing is not done. Another commit for testing.**
=> [aws] Enable winrm when launching Windows instance

tools/windows-node-installer/test/e2e/aws_test.go
We are reading a wrong path in test causing the test
to panic.
/cc @aravindhp @Bowenislandsong @vinaykns
=> [wni] Fix test panics

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
This a follow up PR for #32 . 
This PR enhances the previous added winrm enable at launch feature that it ensures that the winrm port is opened in the security group. If it is not, it will notify the user and add the winrm port to the current security group for the new launched instance so that the winrm port is guaranteed open at launch.
**Testing**
Manual tested with a environment that already has a security group with it. After a new instance launch, it uses the existing security group and add the winrm https port rule to the rule so this instance is ready for Ansible communication.
**Next Step**
The next step is adding a e2e test for both this PR and #32 so that both PR are tested for the ticket.
=> [aws] Ensure winrm port is open

CONTRIBUTION.md
Added an example that illustrates adding
clone fork to the local storage.
=> [docs] Update to Contribution guideline

Makefile, hack/run-wsu-ci-e2e-test.sh
This commit adds a makefile which will be called by the CI job
to run our e2e tests, as well as a placeholder script which kicks
off the tests.
=> [wsu][ci] Add placeholder script and target

tools/windows-node-installer/go.sum, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/test/e2e/aws_test.go
This commit opens SSH port for Windows instance created
This ensures that we can transfer binaries over SCP
to the Windows instance, so that we can run our CI
tests.
Tested manually on my cluster. Need to verify if the e2es pass
/cc @aravindhp @sebsoto @vinaykns
=> [wni] [aws] Open SSH port for Windows instance created

tools/windows-node-installer/README.md
This commit adds the private-key flag to the wni aws create
command
=> [docs] [wni] [aws] Update wni create command with updated flags

internal/test/wmcb_test.go
As of now, we're not using this var, I forgot to remove it. Now, removing it as part of this PR
=> [wmcb] [ci] Remove unnecessary vars

tools/windows-node-installer/README.md
Remove references to keypairs in the docs.
=> [docs] Remove ref to keypairs

hack/run-wsu-ci-e2e-test.sh, tools/ansible/README.md, tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/test/e2e/go.mod, tools/ansible/tasks/wsu/test/e2e/wsu_test.go
This commit results in the WSU bootstrapping the specified Windows
nodes, and adding them to the cluster by accepting their CSRs.
=> [wsu] Run WMCB through WSU

internal/test/framework/framework.go, internal/test/wsu/wsu_test.go
This PR includes:
- Re-adding dropped code to test framework 
- Removing an unnecessary global variable
- Silencing added test noise
=> [ci] wsu test refactor follow-up

internal/test/framework/framework.go, internal/test/go.mod, internal/test/go.sum, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/templates/cni.j2
This commit addresses the problem of the CNI config being statically
generated, when it actually needs to be dynamically generated based
off cluster network settings.
=> [wsu] Dynamically generate the CNI config

internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/powershell/hns.psm1
This commit runs kube-proxy as Windows service, allowing for external
sources to network with pods.
=> [wsu] Run kube-proxy as a Windows service

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
This commit removes the instance password from WNI logs.
=> [wni] Remove secrets from log messages

internal/test/wsu/wsu_test.go
This commit re-adds the WSU running twice in the WSU test suite. The
functionality was mistakingly dropped in commit
65ad3d9d6a6f43e9b9c87b0aba4ab1b676ec814e.
=> [ci] Re-add running WSU twice in the test suite

internal/test/wsu/wsu_test.go
This commit adds a wsu e2e test to check if networking between windows pods on different VMs is working as expected
=> [ci] Add E2E test for Windows east-west networking

tools/windows-node-installer/README.md
Updated readme to reflect correct environment variable for artifact directory
=> [docs][wni] Readme ENV variable fix

CONTRIBUTION.md
Updated contribtion guidelines to include the /hold workflow
=> [docs] Update Contribution Guidelines

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
In Azure, for egress as well as for Loadbalancer service to work,
the windows vm is expected to be placed behind the worker nodes'
load balancer.
this commit puts the azure windows vm behind the worker node loadbalancer
and changes the sku for ip address from basic to standard in order to
successfully carry out the operation
We are using a Standard SKU in place of a Basic SKU as the loadbalancer
and IP SKU should match
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ip-addresses-overview-arm#sku
Also, this PR prints the public and private ip address
for azure and aws VMs to the console
=> [wni] put azure vm behind worker nodes' lb

tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Commit that I missed pushing for #188
=> [wni] Fix unit test changes

Makefile, tools/windows-node-installer/README.md, tools/windows-node-installer/cmd/azure.go, tools/windows-node-installer/go.mod, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/cloudprovider/factory.go, tools/windows-node-installer/test/e2e/aws_test.go, tools/windows-node-installer/test/e2e/azure_test.go, tools/windows-node-installer/test/e2e/common.go
This PR makes the azure WNI API use the credentials passed to it
=> [wni] Make azure WNI use the given credential file

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
This PR modifies WNI to reflect following changes 
- Windows VMs are being tagged after creation. This commit ensures that, VMs are
being tagged with OpenShift tag during creation API call. This will make it
possible to detect VMs for cleanup even after tests are interrupted.
[WINC-406](https://issues.redhat.com/browse/WINC-406)
=> [wni]Fix Windows VM leaks in CI

tools/ansible/docs/aws/aws-with-windows-server.md, tools/ansible/docs/azure/azure-with-windows-server.md, tools/ansible/docs/ocp-4-4-with-windows-server.md
=> [docs] Fix doc spacing typos

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/test/e2e/aws_test.go
Moving towards Machine API, we want to test if we are able to use
public key based ssh authentication to connect and run ssh commands
over windows vm. This PR adds this ssh configuration and sends public key
as a part of userData powershell script while intance creation.
=> [wni] Use SSH key based authentication 

internal/test/framework/windowsvm.go, tools/windows-node-installer/test/e2e/aws_test.go, tools/windows-node-installer/test/e2e/common.go
Test if the key pair change is working properly
=> [ci] Change key pair

internal/test/framework/framework.go, tools/ansible/tasks/wsu/main.yaml, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/types/types.go
Add retries when attempting to configure the SSH client as the VM might still be processing the user data.
=> Bug 1859537: Add retries for SSH config

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/kubelet.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go
This PR adds service dependent stopping and starting in Windows services. It also adds a dependency from kubelet on underlying docker service.
=> [wmcb] add service dependency and service dependent restart

Dockerfile.tools, OWNERS, go.mod, hack/verify-gofmt.sh, internal/test/go.mod
Backports #235 and #237 to release-4.6
=> [release-4.6] Backports from master 20201130

Dockerfile.tools
This PR updates the build and testing base images used in Dockerfile.tools to allow testing locally.
=> [Dockerfile] update base images to allow testing locally

internal/test/wmcb/wmcb_test.go
Sync up to match up with how we are [configuring hybrid-overlay in WMCO](https://github.com/openshift/windows-machine-config-operator/blob/a094884abffac047c1199dce1281969a1e320682/pkg/windows/windows.go#L362):
- Add a sleep to wait for the network reconfiguration to complete
- Change the ordering of reinitialization of the SSH connection
- Remove a stale comment which is remnant of the WNI / WinRM days
=> [test] Fix handleHybridOverlay()

internal/test/windows/windows.go
- Fix returning the output when the command returned an error
- Gracefully handle closing a session that has already been closed
=> [test] Fix windows.Run()

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
* Refactor to make kubelet args unit-testable 
* Allow forcing Windows node object IP
=> [wmcb] Allow forcing Windows node object IP 

Dockerfile.tools
React to upstream CNI changes:
- [build] Install dos2unix for building CNI plugins
Ref: https://github.com/openshift/containernetworking-plugins/commit/623f148
- [build][windows][nodeconfig] Remove flannel.exe
Ref: https://github.com/openshift/containernetworking-plugins/commit/77233dd
=> [Dockerfile] Update WMCO branch to release-4.11

Dockerfile.tools
React to upstream CNI changes:
- [build] Install dos2unix for building CNI plugins
Ref: openshift/containernetworking-plugins@623f148
- [build][windows][nodeconfig] Remove flannel.exe
Ref: openshift/containernetworking-plugins@77233dd
=> [Dockerfile] Update WMCO branch to community-4.9

Dockerfile.tools
React to upstream CNI changes:
- [build] Install dos2unix for building CNI plugins
Ref: https://github.com/openshift/containernetworking-plugins/commit/623f148
- [build][windows][nodeconfig] Remove flannel.exe
Ref: https://github.com/openshift/containernetworking-plugins/commit/77233dd
=> [Dockerfile] Update WMCO branch to release-4.10

OWNERS
- Remove @aravindhp from OWNERS
- Add @selansen to reviewers and approvers
- Add @aravindhp and @ravisantoshgudimetla to emeritus_approvers
=> [OWNERS] Remove @aravindhp and add @selansen

Dockerfile.tools
Update WMCO branch version to community-4.10
Signed-off-by: selansen <esiva@redhat.com>
=> [Dockerfile] Update WMCO branch to community-4.10

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-bootstrapper/pull/358
=> [release-4.10] Add optional parameter for kubelet verbosity

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-bootstrapper/pull/358
=> [release-4.9] Add optional parameter for kubelet verbosity

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-bootstrapper/pull/358
=> [release-4.8]  Add optional parameter for kubelet verbosity
