.gitignore
This addition is needed because we never want to push the contents inside of settings directory.
=> [git] modify gitignore to exclude IDE settings

CONTRIBUTION.md
Add step to pre-PR content that contributor needs to follow before submitting a PR.
=> [docs] Update CONTRIBUTION guideline

tools/windows-node-installer/cmd/aws.go, tools/windows-node-installer/cmd/root.go
The help outputs of flags do not need periods.
Thus, unnecessary periods and spelling mistakes are removed.
=> [wni] cmd help output change

tools/windows-node-installer/cmd/aws.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/factory.go
Refactor interface to be cloud provider agnostic:
As of now, CreateVM method in cloudprovider interface has AWS specific
arguments, removing them to make the cloud provider interface
generic enough across all cloud providers
Should used on top of https://github.com/openshift/windows-machine-config-operator/pull/37/commits/818e3d27c936ba6e3e1fe6400a9924f720b56b7a, the commit to review is https://github.com/openshift/windows-machine-config-operator/pull/38/commits/8abaeb0ac7c67cd28e24effe01c942fad17dc3cb
/cc @aravindhp @Bowenislandsong @vinaykns
=> [wni] Refactor interface to be cloud provider agnostic 

tools/windows-node-installer/pkg/cloudprovider/factory.go, tools/windows-node-installer/pkg/cloudprovider/factory_test.go
Fix the trailing slash error. Without this we would be creating files in
unnecessary directories and cannot read the resources we created 
from the required directories.
/cc @aravindhp @Bowenislandsong
=> [wni] Fix the trailing slash

tools/windows-node-installer/pkg/cloudprovider/factory.go, tools/windows-node-installer/pkg/cloudprovider/factory_test.go
#43 introduced a bug, where we're not checking if the
given path is file or dir and appending trailing "/" while this
should have been normalized, in order to keep us
moving forward, providing this fix which ensures
trailing slash will be added only to directories
/cc @Bowenislandsong @aravindhp @vinaykns
=> [wni] Fix the path validation err

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/test/e2e/aws_test.go
As of now, we don't have tags associated with Windows VM created
This makes it hard for the kubelet to communicate with cloud
provider api and for OpenShift CI jobs to delete the VM
associated with this tag. This commit should solve both
the problems
/cc @Bowenislandsong @aravindhp @vinaykns
=> [wni] Add tags for Windows instance created

docs/README.md, tools/ansible/README.md, tools/ansible/tasks/wsu/main.yaml
This pull request introduces the Windows Scale Up Playbook. The purpose of
this playbook is to prepare a Windows instance to join an OpenShift
cluster, run the WMCB, and ensure that the node has successfully
joined the cluster. Specifically, this pull request implements the
first goal, preparing the instance.
An instance is 'prepared', when it is ready to run the WMCB.
Specifically, when it has a kubelet executable, WMCB executable,
and worker ignition file present on the machine.
=> [wsu] WSU playbook

tools/ansible/tasks/wsu/main.yaml
This commit fixes a bug, where the kubelet exe is not being
copied to the same directory as the rest of the required wmcb files
=> Bug 1760536: [wsu] Fixing kubelet path

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/test/e2e/aws_test.go
This commit adds e2e test for wni's AWS implementation.
The test creates and destroys Windows instance while checking
all required components are created and deleted afterward.
Some functions inside AWS implementation are exposed for this test.
/cc @aravindhp @ravisantoshgudimetla @openshift/openshift-team-windows-containers
=> [wni] add tools e2e test

tools/ansible/tasks/logging/README.md, tools/ansible/tasks/logging/install_fluentd.yml, tools/ansible/tasks/logging/main.yml
This commit sets up an Ansible Playbook to install Ruby Development Kit
and Fluentd on the Windows instance to enable logging.
=> [logging] Install Fluentd on Windows instance

Makefile, docs/README.md
- Add a Makefile target called "build-wmcb-unit-test", that will build a Windows unit test binary
- Update the README with instructions on how to run unit tests
=> [wmcb] Add Makefile target for unit test binary

Makefile, hack/run-wmcb-ci-e2e-test.sh
- Add a Makefile target that will end up getting called by the CI job for running our e2e tests
- Add a placeholder script that will kick off the e2e tests
=> [ci] Add placeholder script and target

tools/windows-node-installer/cmd/aws.go
As of now, we're printing valid flags when an invalid argument
is being passed to wni, for example,  would
not throw an error but valid flag list will be printed. If
those arguments are passed, since it passed the validation
stage, we'd not get an error. This commit removes the
printing of valid flags when the command is run. It'd
rather an error with valid commands available.
The output with this commit:
```
./wni aws delete --kubeconfig kubeconfig --credentials credentials --credential-account xyz 
Create and destroy windows instances in aws
Usage:
wni aws [command]
Available Commands:
create      Create a Windows instance on the same provider as the existing OpenShift Cluster.
destroy     Destroy all security groups and instances specified in 'windows-node-installer.json' file.
Flags: …
```
=> [wni] fix wni aws output

tools/windows-node-installer/cmd/aws.go, tools/windows-node-installer/cmd/azure.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/cloudprovider/factory.go, tools/windows-node-installer/pkg/types/types.go, tools/windows-node-installer/test/e2e/aws_test.go
As of now, we're not providing information to the user
who ran aws wni to access the Windows VM created, this
commit address that problem. We're now printing the
password to access the Windows VM created along with
the public ipadress. We're also adding a new top level
package called types, whose intention is to hold all
the structures that we need to be used across multiple
cloud providers.
/cc @aravindhp @Bowenislandsong @leonjia0112 @vinaykns
=> [aws-wni] Provide credentials to access Windows Node

tools/ansible/tasks/logging/install_plugins.yml, tools/ansible/tasks/logging/main.yml, tools/ansible/tasks/logging/test/logging_test.go
This commit sets up the logging ansible playbook, and
includes functionality for installing the fluentd plugins
required for OpenShift nodes.
=> Fluentd plugins ansible playbook

cmd/bootstrapper/configure_kubelet.go, docs/README.md, pkg/bootstrapper/bootstrapper.go
This change is in preparation for splitting the wmcb functionality into two parts. One part will perform the initial kubelet configuration. The second part will configure OVN CNI.
No new functionality has been added in this commit.
=> [wmcb] Rename "run" command to "configure-kubelet"

Makefile
Fix makefile to include go_build_args for WMCB tests
=> [wmcb] Update Makefile with GO_BUILD_ARGS

tools/ansible/README.md, tools/ansible/tasks/logging/install_fluentd.yml
Currently the module that downloads Ruby installer does not allow redirects,
hence the download does not complete successfully in some cases.
This commit allows the module to accept redirects to solve that problem.
Note: This requires Ansible version 2.9 or higher.
=> Bug 1768568: [logging] Allow redirects for Ruby installer download

Makefile, docs/README.md, test/e2e/bootstrapper_test.go
Replace "run" with "initialize-kubelet" that was introduced in #70.
=> [wmcb] Fix e2e tests that reference "run"

Dockerfile.tools
This commit includes a dockerfile which we can use for test running
within OpenShift CI. This is an attempt to fix the issues we are seeing
with the current CI image, that we cannot install packages in our test
containers, which need ansible and OC. I have opted to not install
ansible, as not all containers need ansible installed, and that can be
done within the individual tests that need it.
This is not guaranteed to work, as the image requirements in the CI docs
are somewhat vague, and its possible that this dockerfile is missing a
CI requirement that is unknown. This can changed in a future commit,
however it is worthwhile to see if this image is usable for our CI jobs
in its current state.
=> Dockerfile for CI

Dockerfile.tools
This commit adds git to the dockerfile used for build_root in CI.
Without git, tests are failing.
=> Add git to build_root dockerfile

Dockerfile.tools
This commit adds make to the dockerfile used for build_root in CI.
Without make, tests are failing.
=> Add make to build_root dockerfile

Dockerfile.tools
This commit is an attempt to fix permission errors in CI. When using
this image, and running `make build` we run into:
`failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied`
This is paired with: openshift/release#5756
=> Specify root user in Dockerfile.tools

Dockerfile.tools
This commit is an attempt to fix permission errors in CI. When using
this image, and running `make build` we run into:
`failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied`
This is paired with: https://github.com/openshift/release/pull/5756
This commit also reverts the previous attempt to fix this:
https://github.com/openshift/windows-machine-config-operator/pull/81
as it did not have any effect on this issue.
=> Specify gocache location in Dockerfile.tools

Dockerfile.tools
This commit switches from using go1.13 to go1.12, as the verify-gofmt
make target does not allow the use of go.13.
This is paired with: openshift/release#5756
=> Use go1.12.13 in Dockerfile.tools

tools/ansible/tasks/logging/test/logging_test.go
This commit add the tests to ensure Ruby and Fluentd are installed correctly
The tests are meant to run on the Windows instance after the logging
playbook has been run successfully against it
=> [logging] E2E tests for logging playbook

Dockerfile.tools, hack/run-wsu-ci-e2e-test.sh
This commit changes the images specified by Dockerfile.tools so that we
can use the openshift_installer_custom_test_image template in OpenShift
CI.
This commit also removes superfluous steps from
hack/run-wsu-ci-e2e-test.sh, that are now being covered in the
Dockerfile
=> Change Dockerfile.tools for new CI template

docs/README.md, hack/run-wmcb-ci-e2e-test.sh, internal/test/go.mod, internal/test/wmcb_test.go, pkg/bootstrapper/bootstrapper.go
As of now, linux pods can be scheduled onto Windows
VM because there is no taint on the node which will
prevent it. This commit addresses that problem
Also, updated the readme with a sample pod
spec for the Windows pods.
~~I'll add an e2e once I start working on the `against the cluster` test suite.~~
Added an e2e which will not be running yet.
=> [wmcb] Register kubelet with Windows taint

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go
As of now, we're not adding worker label to the
Windows Node created. As a result, the node object
in OpenShift cluster has no role associated with it.
This commit addresses that problem.
/cc @aravindhp @sebsoto @vinaykns
=> Bug 1761745: [wmcb] Add worker label to the Windows Node

Makefile, tools/windows-node-installer/README.md, tools/windows-node-installer/go.sum, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/test/e2e/azure_test.go
This commit ensures that winrm Https port is opened on
the windows node and the custom script is executed to ensure
that ansible can talk to the windows node.
=> [wni][azure] Enable and configure the winrm port for windows node

Dockerfile.tools, hack/run-wsu-ci-e2e-test.sh, tools/ansible/tasks/wsu/test/e2e/wsu_test.go
This commit enables wsu e2e tests now that we have an image that is
capable of running them. The image was introduced in:
openshift/release#5842
This commit also changes the Dockerfile, hack script, and the tests
to allow the tests to run properly within OpenShift CI.
=> [wsu] enable e2e tests

pkg/bootstrapper/bootstrapper.go
This commit adds more context to error msgs
when running WMCB. Without this, we're getting
the following error:
{"level":"error","ts":1571786323.7446427,
"logger":"wmcb","msg":"could not run
bootstrapper","error":"The service did
not respond to the start or control
request in a timely fashion."}
With this commit, we should get more
context like,
"failed to start kubelet windows service
with The service did not respond
to the start or control request
in a timely fashion."
=> [wmcb] Add more context to bootstrap error msgs

internal/test/wmcb_test.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go
Change node labels during kubelet registration
from 'node-role.kubernetes.io' to
'node.openshift.io/os_id=Windows'.The main problem
is https://github.com/kubernetes/kubernetes/issues/84912.
There we're restricting the labels to be added
in kubernetes.io namespace. Now, I am changing
it to label that other entities could
watch for like future controllers or query from like
WSU.
The plan is to use this label in WSU in short term. 
Will create a PR for that soon.
=> [wmcb] Change node labels during kubelet registration

pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go
Currently in wmcb, there are few places we are
causing NPE. So this PR will ensure that assert usage
is replaced with require at appropriate places. Also
Nilf is replaces with NoErrorf for more readability.
=> [wmcb] Cleanup assert usage

tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Currently WSU playbook downloads kubelet node binary for Kubernetes version 1.14,
however Kubernetes version is upgraded for OpenShift 4.3, from 1.14 to 1.16.
This commit upgrades Kubernetes node binary version to 1.16.2, and also
introduces an e2e test that checks the checksum of binary downloaded to ensure
the binary was downloaded in its entirety.
=> Bug 1775384: [wsu] Upgrade kubelet version to 1.16

tools/windows-node-installer/pkg/resource/tracker_test.go, tools/windows-node-installer/test/e2e/aws_test.go, tools/windows-node-installer/test/e2e/azure_test.go
In wni there are few places we are causing NPE, so this PR will ensure assert usage is replaced with
require at appropriate places. Also replaced condition checking on the err with assert/require in aws e2e.
=> [wni] Cleanup assert usage

test/e2e/bootstrapper_test.go
This is another minor fix for assert vs require usage in the
wmcb test files. This got missed addressing in the original
PR #97 . Thx aravindh for catching this out.
=> [wmcb] minor assert fix

tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/test/e2e/wsu_test.go
https://github.com/openshift/windows-machine-config-operator/pull/87
works only ocp 4.2 or less. In 4.3, the nodeadmission restriction
plugin is blocking nodes to register themselves with worker
labels. So, I am moving the labelling part to WSU. The
eventual goal is to move this to a controller which
is capable of watching for the WMCB label and apply
worker labels.
xref: https://github.com/openshift/windows-machine-config-operator/pull/94
/cc @aravindhp @sebsoto @suhanime
=> [wsu] apply worker roles

tools/ansible/tasks/wsu/test/e2e/wsu_test.go
This commit switches from using an Intel instance type to using an
AMD instance type when spinning up a VM for our e2e tests.
This is being done as the hybrid overlay executable for Windows,
needed to prepare Windows instances to join a cluster using OVN,
cannot currently be run on Intel instances due to a bug in the
Intel 82599 network driver.
=> [wsu] Switch to AMD instance type for e2e tests

hack/run-wsu-ci-e2e-test.sh
This commit configures hybrid networking for the WSU e2e tests. This
will allow us to join Windows nodes to the cluster.
=> [ci] Setup hybrid networking in WSU e2e tests

hack/run-wsu-ci-e2e-test.sh, tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/test/e2e/wsu_test.go
This commit results in the WSU downloading and running the OVN hybrid
overlay executable. In addition the commit includes a test to ensure
that the overlay was able to run properly, by checking to make sure the
proper annotation has been added to the node.
I have also edited the hack script and dockerfile so that we can edit
the OpenShift network operator in our tests to include a hybrid overlay
configuration.
=> [wsu] Run the OVN hybrid overlay

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go
As of now, we're not creating pod manifest dir
causing kubelet to throw error
`Unable to read config path
c:\\k\\etc\\kubernetes\\manifests: path
does not exist, ignoring
error`. This commit should resolve that.
=> Bug 1768835:  Fix pod manifest directory creation

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go
WMCB code has used [path](https://golang.org/pkg/path/) library at many places,
however, [filepath](https://golang.org/pkg/path/filepath/) should be used whenever we are targeting file systems.
This commit changes the implementation to use filepath wherever relevant.
WMCB code was setting the kubelet argument for certDirectory with non-Windows
path separator. This commit fixes it.
Added Unit Test for path separator of cloud.conf
Added E2E test for paths in kubelet arguments. Excluded checks for
values of node-labels and pod-infra-container-image
Code reorganization:
Changed func getSvcState in bootstrapper e2e to func getSvcInfo,
repurposing the code to fetch service path along with state.
=> [wmcb] Fix path separators for Windows paths

tools/windows-node-installer/README.md, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/test/e2e/azure_test.go
**Problem**:
WNI when creating VMs were overwriting the rules present in the  worker NSG causing due to which we were losing access to the OpenShift  console as the existing rules are required for console access.
**Solution:** 
Rather than updating the security group, the code has been  modified to just create / update the rules. To achieve this, the following was done:
- Remove all instances of updating the worker security group
- Introduce a struct that encapsulates an Azure NSG security rule from a WNI perspective
- Add methods to the struct that create/update and delete the rules
- GetMyIP() was exported to allow it be called from the e2e test code
=> [wni][azure] Fix rule handling

internal/test/framework/framework.go, internal/test/go.sum, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml
This commit run the wmcb's configure-cni command on the bootstrapped
nodes. In addition it distributes the files needed to run the command to
the nodes.
This commit also adds an e2e test to the wsu test suite, which deploys
Windows and Linux pods, and ensures they can communicate between each
other.
=> [wsu] Configure CNI on bootstrapped nodes

internal/test/wmcb/wmcb_test.go
In addition to checking that "FAIL" is not present in the test output, add a check that "panic" is not present. We also inspect the exit code returned by the remote binary. This allows us to catch test failures that don't print out "FAIL" like "CommandNotFoundException"
To help with debugging we are now printing out the complete output of the remote test run.
=> [ci] Improve WMCB unit test failure checking

internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml
**Problem**:
The execution of the hybrid-overlay.exe is failing in the Windows node as it cannot find the required `k8s.ovn.org/hybrid-overlay-hostsubnet` annotation on the node object that should be applied on enabling hybrid OVN networking.
**Solution**:
The hybrid annotation has changed to `k8s.ovn.org/hybrid-overlay-node-subnet` in 4.4 and to pick those changes up we need to use a newer version of the hybrid-overlay.exe. A [release](https://github.com/openshift/windows-machine-config-operator/releases/tag/v0.3-alpha) was cut that included the newer version built from the master (4.4) branch of openshift/ovn-kubernetes and WSU was updated to use this
version.
**Jira**: [WINC-194](https://issues.redhat.com/browse/WINC-194)
=> Bug 1787646: Update hybrid-overlay.exe for 4.4

internal/test/framework/framework.go, internal/test/framework/windowsvm.go, internal/test/wmcb/main_test.go, internal/test/wmcb/wmcb_test.go, internal/test/wsu/main_test.go, internal/test/wsu/wsu_test.go
Currently our framework spins up only 1 windows instance. We need to have multiple Windows instances to check communication between instances, or run WSU with different arguments. This commit changes the framework to allow it to spin up multiple Windows instances.
As a part of this commit,
- Encapsulate Windows VM is its own struct and interface separate from the  framework. This clearly separates the framework from the tests.
- Add a slice of the WindowsVM interface to the framework
- Setup takes the number of instances to be spun up as a parameter, and  TearDown destroys all instances in the slice
- In WSU and WMCB test files, the tests now run in a loop against the instances  in the slice
Some parts of the PR were added by @suhanime
Signed-off-by: Suhani Mehta <sumehta@redhat.com> …
=> [ci] Update framework for launching multiple VMs

hack/run-wmcb-ci-e2e-test.sh, hack/run-wsu-ci-e2e-test.sh, internal/test/framework/framework.go, internal/test/framework/windowsvm.go, internal/test/wmcb/main_test.go, internal/test/wsu/main_test.go, tools/ansible/README.md
- Allow passing an array of Credentials to the framework which allows tests to run against existing VMs without them being created or destroyed by the framework.
- Add an option to skip configuration steps for the VMs
These options are useful during development.
=> [ci] Add options for working with existing VMs

hack/run-wsu-ci-e2e-test.sh, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml
This commit ensures that the WSU can be run against the same VM multiple
times without failing.
- Removes the requirement for CSRs to be found. CSRs will only be
present on the initial WSU run.
- Kills existing hybrid-overlay processes before starting a new one, so
that multiples will not exist.
- Removes the kube-proxy service, so that a new kube-proxy executable
can be used if it was changed.
This commit also now has the WSU test suite being run twice against each
VM. Because of that I had to double the test timeout
=> Bug 1776506: Allow WSU to be run multiple times

hack/run-wmcb-ci-e2e-test.sh, hack/run-wsu-ci-e2e-test.sh
`skipVMSetup` was incorrectly referenced as `skipSetup` in the bash scripts. This PR fixes that.
=> [ci] Fix skipVMSetup command line option

internal/test/framework/framework.go, tools/windows-node-installer/test/e2e/aws_test.go
This commit updates the ami that we use for spinning up a Windows VM in
our wsu and wni e2e tests. The previous ami was removed, so this is a
short term fix to get e2e tests working. A longer term solution would be
finding the latest ami to use, but that will be featured in a future
commit.
=> [ci] Update Windows VM ami

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/types/types.go
This commit ensures that we capture the user information that is used to
access the windows instance. This can be useful when working on the e2e
test cases, especially when interacting with windows VM via winrm client.
Username also varies with cloudprovider, so it would be good to include it
in the credential object.
=> [wni][aws][azure] Capture windows user in credentials

tools/windows-node-installer/test/e2e/aws_test.go
This commit ensures that only a single instance is created and
implements all the prerequisite steps in a setup function.
=> [wni][aws] Avoid creating another instance in e2e

Dockerfile.tools, tools/ansible/tasks/wsu/main.yaml
As of now, we're not mapping OpenShift version to WMCB
versions. Without this PR, we'd have to maintain multiple
branches and backport changes. As of now, it doesn't
make sense to maintain branches and backport changes,
in future, we can get started on branching and
picking changes
Logic involved for semver:
curl -s
https://api.github.com/repos/openshift/windows-machine-config-operator/releases
gets the list of all releases, we use the cluster
version from 'oc version' to filter out the release
we need.The wmcb release tags are supposed
to confirm to the following semver format.
v\<openshift-major-version\>.\<openshift-major-version\>.
\<wmcb_build_number\>-\<release_type\>.
For example, v4.4-1-alpha.
For a \<openshift-major-version-version\>.\<openshift-minor-version\>,
there can be many …
=> Map OpenShift release version to WMCB version to support OpenShift 4.3

docs/README.md, hack/run-wmcb-ci-e2e-test.sh, internal/test/framework/framework.go, internal/test/wmcb/powershell/wget-ignore-cert.ps1, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go
- [ci] Move common entities to the framework
Move ClusterAddress and intializing it into the framework. Do the same for RetryCount, RetryInterval and WindowsLabel into the framework as  they will be required by both WSU and WMCB test suites.
- [wmcb] Fix e2e tests
- TestBootstrapper ends up calling initialize-kubelet twice resulting in two bootstrap CSRs being issued. This is problematic when running this in CI as the test runner needs approve all CSRs. Rather    than doing that this test needs to be split up or called twice from the runner.
- testConfigureCNIWithoutKubeletSvc assumes the presence of the CNI dir and config when it is run. This test is called from TestBootstrapper at which points the required files are not created. Fix the test to create a temp CNI dir and config.
- …
=> [ci] Enable running of bootstrapper tests

tools/windows-node-installer/README.md, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
**Problem**
To launch the instance, the first public subnet was being picked. In the case where the instance type is not supported in the availability zone the subnet is in, the instance creation would fail.
**Solution**
Rather picking the first public subnet, we further cross reference with the list of instance offerings and ensure we pick the subnet that is in a zone that supports the instance type.
Jira: [WINC-149](https://issues.redhat.com/browse/WINC-149)
=> [wni][aws] Fix subnet selection

tools/windows-node-installer/README.md, tools/windows-node-installer/cmd/aws.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/test/e2e/aws_test.go
This commit makes it so that if an imageId is not provided to the WNI,
the latest Windows Server 2019 with Containers image will be used. This
is being done so that we can run outside the us-east-1 region, as
imageId's are region specific.
=> [wni] Use latest Windows image

internal/test/framework/framework.go, internal/test/framework/windowsvm.go, internal/test/go.mod, internal/test/go.sum, internal/test/test.go, internal/test/wmcb/templates/cni.template, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go
This PR enables remotely running WMCB configure-cni tests on the test Windows VM. The following changes were added to achieve this: 
- [ci] Add RunOverSsh and Reinitialize to WindowsVM
- [ci] Add functions that pull release information
- [ci][wmcb] Enable running of CNI tests
=> [ci] Enable running of WMCB CNI e2e tests

internal/test/go.mod, internal/test/go.sum
Test builds are failing as the WNI they pull in still reference the old
name for the repository. This commit bumps the imported WNI to the
latest commit to avoid that problem.
=> [ci] Bump imported WNI to after repo rename

internal/test/framework/framework.go, internal/test/framework/windowsvm.go, internal/test/wmcb/main_test.go, internal/test/wsu/main_test.go, internal/test/wsu/wsu_test.go
As of now, we are not retrieving the log files for
kubelet and wsu after wsu, wmcb are run. This commit
should address the issue.
- Added a basic implementation of retrieve files in Windows VM
- Updated TestMain to call retrieve files in WSU, WMCB
- Add functionality to collect wsu output
As of now, we're not collecting log files
related to wsu runs. This commit should
address this issue.
Co-authored-by: Sebastian Soto <ssoto@redhat.com>
=> [ci] Save log files from output run

internal/test/go.mod, internal/test/go.sum
This commit makes the test framework use the latest WNI, to pick up the
changes made to not log instance secrets. This commit was done by
deleting the WNI line from go.mod, and then running `go mod tidy`.
=> [ci] Use latest WNI

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Problem: SG rules do not get updated when local IP changes(When user switches
from one IP to another the required rules for current IP are not added to SG).
Solution: Get the missing rules from the list of rules matching local IP,
set the missing rules in Security Group while preserving any existing rules.
Bug: [WINC-187](https://issues.redhat.com/browse/WINC-187)
=>  [wni][aws] Add missing rules to Security Groups 

internal/test/wsu/main_test.go, tools/ansible/tasks/wsu/main.yaml
Problem: When we run wsu playbook parrallely for 2 windows vms, the ansible task
'Move wmcb to temporary directory' fails for the second vm. This is because
currently we are building wmcb.exe in the project root directory in both the runs.
So when the run for the first vm has moved the built wmcb.exe to a temporary
directory, run for the second vm cannot find it.
Solution: Instead of moving built wmcb.exe to a temporary directory, we are
copying it
=> Bug 1805513: Resolve parallel execution of playbook

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Problem: Unit test faiure occurs due to the bug in checking a scenario created
as a part of the ticket WINC-187: SG rules do not get updated when local IP 
changes.
Solution: Remove this test case and add unit tests for another function ExamineRulesInSg()
to appropriately handle and test the scenario of nil rules being passed to the function.
Bug: WINC-236
=> [wni][aws] Fix unit test failure for WINC-187 merge

internal/test/framework/windowsvm.go, internal/test/wsu/main_test.go, internal/test/wsu/wsu_test.go, tools/ansible/README.md, tools/ansible/tasks/wsu/main.yaml
This PR enables WSU to download the latest WMCB, hybrid-overlay and kube node binaries based on the cluster version
To achieve this, first commit introduces TestWindowsVM interface that composes WindowsVM interface. The second commit then introduces a property to TestWindowsVM interface that is used for e2e-wsu tests
Since CI cluster does not give `oc version` in the format of 4.x, kubernetes (server) version is used to map to the corresponding OpenShift version
WSU can now choose to build wmcb or download it based on a boolean argument
E2E SHA check now happens for wmcb (downloaded), hybrid-overlay and kube node binaries, as a part of the playbook
- e2e-wsu tests changed to bring up 2 VMs
- Add property `buildWMCB` to Windows VM interface
- Specialize framework setup for wsu_test.go
- …
=> [wsu] Autodownload binaries based on cluster version

tools/ansible/README.md
This PR documents the workaround for API rate limit being exceeded when running WSU
Problem: WSU playbook fails to run in TASK [Get release]. This happens due to github rate-limiting unauthenticated API calls at 60 request/hr.
WSU playbook calls github API to fetch releases for WMCB.
Workaround: Wait for rate-limit to reset before running WSU playbook again (at most 1 hour)
=> Bug 1798441: [wsu] Document API rate limiting error

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/cloudprovider/factory.go
As of now, we're deleting the entire Windows VMs created via WNI using
windows-node-installer.json. We'd want a way to just delete a single
Windows VM created via WNI so that we can use it in WMCO. This commit expands
the interface to have that method.
/cc @aravindhp @openshift/openshift-team-windows-containers
=> [wni] Add a DestroyWindowsVM method to cloud provider interface

internal/test/framework/framework.go, internal/test/framework/windowsvm.go, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml
This PR captures the kube-proxy logs in C:\k\log\kubeProxy\ and the hybrid-overlay logs in C:\k\log\hybridOverlay\ in the remote VM logs directory .
Kube proxy logs are already being captured so they will just be redirected to this new directory and hybrid overlay logs are captured using RedirectStandardError and RedirectStandardOutput arguments in the WSU playbook while the binaries are running. 
This PR also consists addition of  a method RetrieveDirectories to the WindowsVM interface, this was required as the remote log directory on the VM can now consist of a nested directory structure which should be copied to the artifacts directory. 
The E2E test  make sure that the log directories and files are being captured in C:\K\log on the VM. …
=> [wsu] [CI] Capture hybrid-overlay and kube-proxy output in artifacts_dir

internal/test/framework/windowsvm.go
https://github.com/openshift/windows-machine-config-bootstrapper/pull/157 caused the functionality of testing using existing WindowsVMs broken. This commit should address that. Tested this locally and it works fine.
=> fix windows struct nil pointer

internal/test/framework/framework.go, internal/test/wmcb/main_test.go, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml
Currently, we are hard coding the CNI plugins version to 0.8.2. This PR makes
wsu playbook dynamically pick the latest 0.8.x version of CNI plugins from repo's
release page.
=> [wsu] Download latest 0.8.x version of CNI plugins

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/types/types.go, tools/windows-node-installer/test/e2e/azure_test.go, tools/windows-node-installer/test/e2e/common.go
This PR opens up the SSH port for local IP of the user and installs OpenSSH server on the windows node for Azure VMs. This PR includes e2e tests for testing OpenSSH connections on Azure VMs
=> [wni] Enable SSH networking for windows node

hack/run-wsu-ci-e2e-test.sh, internal/test/wsu/wsu_test.go
This reverts commit 6467b06598ee868d6508c41dc90e859e6761bef4. This
commit will be able to be merged once
https://bugzilla.redhat.com/show_bug.cgi?id=1789881 has been fixed.
This revert is being done since the commit was made only to workaround
the above mentioned bug.
=> [ci] Revert OVN workaround

tools/ansible/tasks/wsu/main.yaml
This PR resolves the access to kube-proxy error encountered while running WSU
playbook multiple times accross the same set of VM's
Problem: WSU playbook fails to run in TASK [Copy kube-proxy to C:\k] with the error
"Access to the path 'C:\\k\\kube-proxy.exe' is denied".
Solution: This is happening because kube-proxy is in use. This is fixed by moving
the `Ensure kube-proxy Windows Service is not running` to execute before the
`Copy kube-proxy to C:\k` task.
Bug: [1809291](https://bugzilla.redhat.com/show_bug.cgi?id=1809291)
=> Bug 1809291: [wsu] Ensure kube-proxy service is not running.

Dockerfile.tools, Makefile, go.mod, hack/verify-gofmt.sh, tools/ansible/tasks/wsu/main.yaml, tools/windows-node-installer/go.mod
This PR fixes the shell command for extracting the kubernetes version without patch version for any
intermediate releases eg: v1.18.0-rc.1 should be extracted as 1.18 instead of 1.18.0-rc for forming
the changelog URL.
In addition it also makes the changes necessary in go.mod, verify-gofmt.sh and Dockerfile to update golang version from 1.12 to 1.13. 
Since the golang version has been updated in CI we need to unset the GOFLAGS environment variable where it is set to "-mod=vendor" value to avoid vendoring in CI environment.
=> Bug 1821429: [wsu] Fix getting kube node binary SHA

internal/test/wsu/wsu_test.go, tools/ansible/README.md, tools/ansible/tasks/wsu/main.yaml, tools/windows-node-installer/test/e2e/azure_test.go
this commit changes the wsu to get the node name
from private ip of the vm if the public ip doesn't
exist
Co-authored-by: pratikmahajan <pratik@mahajan.xyz>
Taken from https://github.com/PratikMahajan/windows-machine-config-bootstrapper/commit/57e707510dad4f4a7d38d599da1ef522bf4895dc
=> [wsu] get node name from public or private ip

tools/windows-node-installer/pkg/types/types.go
We are noticing that commands run using Run() that uses a WinRM client is taking more than 5 minutes to complete after the hybrid-overlay reconfigures the network. Reinitialize the WinRM client in the Reinitialize() method to mitigate this.
Add a "warning" pre-fix to the log message printed on errors encountered when reinitialzing the SSH client to call out that this is not a fatal error.
=> [wni] Update Reinitialize() to handle WinRM client

Dockerfile.tools
This commit fixes hack script failure while running inside ci image due to
insufficient permissions for creating the cache directory
Fix includes creating the cache directory and setting GOCACHE env while
creating the image
=> [ci] Fix permission issue in WSU e2e script

Makefile, tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
https://github.com/openshift/windows-machine-config-bootstrapper/pull/165/commits/48d69e8bd2b2801c42ab7c299a41cbf03d6a46a7 introduced the change which broke the unit tests. This commit ensures aws unit tests pass now
/cc @PratikMahajan @aravindhp @openshift/openshift-team-windows-containers
=> [wni] Fix unresolved ssh port in unit tests

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
This PR has 2 commits:
0856135 - Switches to using ec2 inteface which makes mocking easier
2fdb7ef - Return immediately from the CreateWindowsVM when the instance is not running instead of waiting till timeout
=> [wni] Return error on AWS instance state changes during CreateWindowsVM call

Dockerfile.tools, hack/run-wmcb-ci-e2e-test.sh, hack/run-wsu-ci-e2e-test.sh, internal/test/framework/framework.go, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go
The oc binary is no longer injected into src image in the CI step registry world. There is no reason for us to use oc when we can achieve the same functionality using the API.
- Get the cluster address using API calls
- Removing patching of the network.operator CR as this needs to be  removed anyhow.
This is needed for https://github.com/openshift/release/pull/8623/
Based on openshift/windows-machine-config-operator#47
Co-authored-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>
=> [ci] Remove dependency on oc binary

Dockerfile.tools
- Bring back downloading and installing oc in Dockerfile.tools. This is   needed by the WSU playbook and was erroneously removed in #192.
- Create Ansible tmp directory with user accessible permissions.
=> [ci] Step registry fixes

internal/test/framework/framework.go, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go, tools/ansible/tasks/wsu/main.yaml, tools/ansible/tasks/wsu/templates/cni.j2
As of now, the ovn-kube network already comes with hybrid overlay enabled. So, we don't need to patch the network operator as the cluster comes up with hybrid overlay enabled. While patching we previously used to wait till all the nodes have hybrid-overlay specific annotations. In the new OVN world, the linux nodes won't have those annotations present, so the test was failing for us. This commit
- Removes the test which fails if we have don't those annotations
on master nodes
- Removes patching the network operator object
- Removes the test which checks for the WSU failure when hybrid overlay
is not enabled
=> Bug 1823919: [ci] React to upstream kube-ovn changes

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
This commit handles the AWS session creation error instead of panicing.
The previous implementation used `Must()` which asserts that the wrapped
function did not return an error and panics if it did. I removed that so
that we can bubble up the returned error and handle it gracefully.
=> [wni] Don't panic on AWS session creation error

internal/test/framework/framework.go, internal/test/wmcb/pkginfo.go, internal/test/wmcb/wmcb_test.go
This PR consists of 2 commits 
- Create an interface to generalize adding packages in the wmcb tests. Implement Factory pattern to retrieve package specific instances.
- The PR also ensures that tests use kube node package with the current k8s version
**Problem**: wmcb e2e tests use kube-node packgage with hardcoded version.
**Solution**: Use current kubernetes version to retrieve node package
for Windows. The corresponding SHA is retrieved using changelog.
[WINC-235](https://issues.redhat.com/browse/WINC-235)
=> [wmcb] Dynamically pick the kube-node package in the e2e tests

tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/test/e2e/azure_test.go
this PR changes the retrieval of backendPoolID to fetch the
backendPoolID in a programmatic way.
also, adds a method to disassociate ip address from NIC as the changes
introduced in the PR broke the deleteVM function
also, added tests to check the backendPoolID of the VMs created
[WINC-319]
=> [wni] Add programmatic retrieval of backendPoolID

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/main.go, tools/ansible/tasks/wsu/main.yaml
Currently, all WMCB logs are redirected to stderr by [default](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/log/zap#Options), including info level logs. This PR redirects info level logs to stdout and errors are redirected to stderr.
As a part of this PR:
- wmcb code changes for redirecting info logs to stdout and errors to stderr
- wsu changes to react to wmcb changes
=> Bug 1818026: Redirect WMCB info logs to stdout

internal/test/go.mod, internal/test/go.sum
Wmcb tests import wni module. This commit ensures that latest changes of wni
are reflected in wmcb
=> [wmcb] Bump wni version to reflect latest changes

tools/ansible/tasks/wsu/main.yaml
This PR fixes two issues encountered while running
WSU with kube version v1.18.3+144c666. The redundant
part in the kube version needs to be trimmed to get the
correct kubernetes version in the grep command.
In addition, since the output of the curl command is no
longer in `<td><code>...</code></td>` format but in
`<td>...</td>` format the sha needs to be extracted
accordingly.
=> Bug 1841140: fix getting kube node binary SHA

tools/ansible/README.md, tools/ansible/docs/ocp-4-4-with-windows-server.md
We only support using the absolute path in the kubeconfig environment variable for the WSU playbook. Specifying the relative path will cause the playbook to fail.
=> Bug 1778714: [docs] Call out kubeconfig path usage

tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go, tools/windows-node-installer/pkg/cloudprovider/azure/vm.go, tools/windows-node-installer/pkg/cloudprovider/factory.go
As of now, we're using CreateWindowsVM which couples Windows VMs creation along
with attaching it to public subnet. This will not be ideal to us when we are
moving to machine-api in the WMCO world. Machine-api allows the VM to be created
only on the private interface. So, in order to mimick that functionality, this
commit expands the Cloud interface with a method called
CreateWindowsVMWithPrivateIP which allows the WindowsVMs to be created on the
private subnet and won't attach a public IP to the VM created.
=> [wni] Expand Cloud interface

internal/test/wmcb/powershell/wget-ignore-cert.ps1, internal/test/wmcb/wmcb_test.go, tools/ansible/tasks/wsu/main.yaml
The MCO team have started moving to ignition v3 spec in MCS. For 4.6 timeframe,
they are supporting both v2 and v3. As a result, MCS now requires user-agent
in the header to tell which version of ignition spec to be served by MCS.
This PR modifies the powershell script to include a new parameter for the
user-agent header
=> [wsu] [ci] Add user-agent for ignition url

hack/run-wmcb-ci-e2e-test.sh, internal/test/framework/framework.go, internal/test/wmcb/pkginfo.go, internal/test/wmcb/wmcb_test.go, internal/test/wsu/wsu_test.go
Remove the dependency on having an hybrid-overlay-node.exe and kubelet.exe being in a GitHub release by:
- Building it the hack script
- Copying the binaries to the Windows VM instead of remote downloading it from the release URL
- Move GetClusterVersion() and GetLatestWMCBRelease() from framework.Setup() into the wsuFramework.Setup()
=> [e2e] Remove hybrid-overlay/kubelet release deps

pkg/bootstrapper/bootstrapper.go
The pause pod image we're using now doesn't include 1909 and 1903 images causing
problems when pod sandbox is getting created for those Windows builds. This
should fix the problem
Ref: https://github.com/kubernetes/kubernetes/issues/87339#issuecomment-582136209
=> [wmcb] Add 1.3 pause pod image

Dockerfile.tools, go.mod, hack/verify-gofmt.sh, internal/test/go.mod
This commit does the following things:
- Updates go.mod file to go 1.15
- Updates hack/verify-gofmt.sh to check for go version 1.15
- Replaces FROM directives in Dockerfile.tools with
registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.6
=> WINC-460: Update to Go 1.15

internal/test/wmcb/wmcb_test.go, pkg/bootstrapper/bootstrapper.go
This commmit ensures that we fix the issue created by PR [#239](https://github.com/openshift/windows-machine-config-bootstrapper/pull/239)
where a Windows Node goes to a `NotReady` state, when kubelet
is updated. The issue was caused by cloud-provider kubelet arg
getting overridden by an empty string. `initializeKubeletFiles` function
was not being called during update kubelet, since all files are already
present in the VM, however the function was also responsible for setting
cloud-provider arg. To resolve this issue, this commit makes changes
to call the  `initializeKubeletFiles` function during update. It is
also required to stop an already running kubelet service before
`initializeKubeletFiles` is called to avoid file access errors. The
commit also adds tests to check for `Ready` …
=> Bug 1894649: Fix Node NotReady state when updating Kubelet service.

Dockerfile.tools
This ensures the testing in this repository uses the same commits of the
submodule components as the operator does.
=> Dockerfile.tools: Clone WMCO repo and build submodules from there

internal/test/wmcb/wmcb_test.go, pkg/bootstrapper/bootstrapper.go
This commmit ensures that we fix the issue created by PR #239
where a Windows Node goes to a NotReady state, when kubelet
is updated. The issue was caused by cloud-provider kubelet arg
getting overrided by empty string. initializeKubeletFiles function
was not being called during update kubelet, since all files are already
present in the VM, however the function was also responsible for setting
cloud-provider arg. To resolve this issue, this commit makes changes
to call the  initializeKubeletFiles function during update. It is
also required to stop an already running kubelet service before
initializeKubeletFiles is called to avoid file access errors. The
commit also adds tests to check for Ready state for Windows Node.
(cherry picked from commit a22ec439c9a447b26f414b7ee11a5ec1b61c4920)
=> Bug 1894649: [community-4.6] Fix Node NotReady state when updating Kubelet service.

Dockerfile.tools
This ensures the testing in this repository builds and uses the
containernetworking-plugins, kubernetes, and ovn-kubernetes binaries
from the commits pinned in their respective submodules in the WMCO repo.
Backport of #242
=> [community-4.6] Dockerfile.tools: Clone WMCO repo and build submodules from there

cmd/bootstrapper/main.go
This change was made to raise WMCB errors as a proper failure
(top-level exit call) instead of just logging them to stderr.
=> Bug 1903330: WMCO successfully reconciles with incorrect configure-cni command

.ci-operator.yaml
This commit allows us to change the build_root_image with commits to
this repo. This is to maintain consistency with the WMCO repo and to
not require explict changes to openshift/release during go version update.
=>  [ci] Define build_root_image within WMCB repo

Dockerfile.tools
This ensures the testing in this repository builds and uses the
containernetworking-plugins, kubernetes, and ovn-kubernetes binaries
from the commits pinned in their respective submodules in the WMCO repo.
Backport of https://github.com/openshift/windows-machine-config-bootstrapper/pull/242
=> [release-4.6] Dockerfile.tools: Clone WMCO repo and build submodules from there

pkg/bootstrapper/bootstrapper.go
This requires upgrading the pause image to 3.4.1 which has support for Windows Server 20H2.
=> WINC-555: [wmcb] Support Windows Server 20H2

cmd/bootstrapper/uninstall_kubelet.go, internal/test/wmcb/wmcb_test.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/kubelet.go, test/e2e/bootstrapper_test.go, test/e2e/uninstall_kubelet_test.go
This PR  adds a command line option "uninstall-kubelet " to uninstall the existing kubelet service from the Windows node. This will help in BYOH implementation to uninstall all services.
=> [wmcb] Add uninstall kubelet command line option

Dockerfile.tools, test/e2e/configure_cni_test.go
https://github.com/openshift/windows-machine-config-operator/pull/395 renamed the kubernetes submodule to kubelet. Reflect that here and update the CNI configuration check
=> Reflect WMCO kubelet submodule change

pkg/bootstrapper/bootstrapper.go
Windows base images tend to be very large, so to accommodate this add `--image-pull-progress-deadline=30m` to the kubelet args. This alleviates the requirement for pre-pulling images.
Needed for https://github.com/openshift/windows-machine-config-operator/issues/205
=> WINC-541: [wmcb] Increase image pull deadline in kubelet

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/modules.txt
Ran:
- `go get "github.com/gogo/protobuf"`
- `go mod tidy && go mod vendor`
Fixes rhbz#1924039
=> Bug 1924039: [vendor] Update to github.com/gogo/protobuf:v1.3.2

pkg/bootstrapper/bootstrapper.go, test/e2e/bootstrapper_test.go
The "openshift-managed" string must be added to the description of all
Windows services created as part of the Windows Node configuration
process. This is a requirement of properly upgrading Nodes. During the
upgrade process, a search can be done for all Windows services with the
string in their description, in order to identify and potentially remove
Services created by us.
=> WINC-724: Add OpenShift managed to Kubelet SVC description

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go
This requires upgrading the [pause image to 3.6](https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md#36)
which has support for Windows Server 2022.
=> WINC-602: [wmcb] Support Windows Server 2022

Dockerfile.tools, cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, hack/run-wmcb-ci-e2e-test.sh, internal/test/wmcb/deploy/job.yaml, internal/test/wmcb/main_test.go, internal/test/wmcb/wmcb_test.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, pkg/internal/containerd_conf.toml, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
This PR adds the --dockerRuntime flag option to allow passing containerd specific kubelet config params
while starting kubelet service. This will also allow kubelet to set a dependency on the underlying container runtime present.
It also starts using the DOCKER_RUNTIME env var passed from the release repo in the CCM job config to set the flag value for --dockerRuntime and install containerd Windows service to test the kubelet config changes.
=> WINC-696: Introduce dockerRuntime flag option to update kubelet arguments 

cmd/bootstrapper/configure_cni.go, cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, hack/run-wmcb-ci-e2e-test.sh, internal/test/wmcb/deploy/job.yaml, internal/test/wmcb/main_test.go, internal/test/wmcb/wmcb_test.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/configure_cni_test.go, test/e2e/uninstall_kubelet_test.go
This PR reverts the addition and usage of dockerRuntime flag option. It was added with the anticipation of using docker and containerd runtimes in the same release.
However containerd feature is now expected to be fully supported in 6.0 time-frame while removing support for docker container runtime which makes this flag option no longer useful.
=> Revert addition of dockerRuntime flag

OWNERS
- Remove @selansen from OWNERS
- Add @aravindhp to reviewers and approvers
- Remove @aravindhp from emeritus_approvers
=> [OWNERS] Remove @selansen and add @aravindhp

.ci-operator.yaml, Dockerfile.tools, go.mod, hack/verify-gofmt.sh
This change bumps the Go version to 1.18.
Follow-up to https://github.com/openshift/windows-machine-config-operator/commit/c322f973a8ea7bd95a85e9f2d10d2b5687aa7eb9
Ran:
`go mod edit -go=1.18 && go mod tidy && go mod vendor`
=> Bump Go version to 1.18

hack/run-wmcb-ci-e2e-test.sh
This change turns on the automatic Pod Security label synchronization by adding the recommended labels in the default namespace. Follow up to openshift/windows-machine-config-operator@fed9c3cfb0f259316cb7a62eb288b4ed9e2a293f
=> WINC-879: [hack] Add the pod security labels in default namespace

cmd/bootstrapper/initialize_kubelet.go, cmd/bootstrapper/uninstall_kubelet.go, pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/bootstrapper_test.go, test/e2e/bootstrapper_test.go, test/e2e/uninstall_kubelet_test.go
This change introduces an optional program argument to
set the kubelet log level. If unset, wmcb.exe will use
the verbosity value in the kubelet systemd unit provided
by the ignition file (if any) or default to 3. The novel
program argument takes precedence over the later two.
=> Add optional parameter for kubelet verbosity
